<div class="col-sm-3 col-lg-3">
    <div class="dash-unit">
        <dtitle>Adtenda Última Comanda</dtitle>
        <hr>
        <div class="framemail">
            <div class="window">
                <ul class="mail">
                    <?php 
                    include "incs/adtenda_terrassa.inc";
                    include "incs/adtenda_linia.inc";
                    include "incs/desconexio.inc";
                    
                    include "incs/adtenda_bornfruits.inc";
                    include "incs/adtenda_linia.inc";
                    include "incs/desconexio.inc";
                    
                    include "incs/adtenda_guerrero.inc";
                    include "incs/adtenda_linia.inc";
                    include "incs/desconexio.inc";
                    
                    include "incs/adtenda_garbi.inc";
                    include "incs/adtenda_linia.inc";
                    include "incs/desconexio.inc";

                    include "incs/adtenda_veron.inc";
                    include "incs/adtenda_linia.inc";
                    include "incs/desconexio.inc";
                   
                    ?>
                </ul>
            </div>
        </div>
    </div>
</div>